# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-27 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('log_in', models.CharField(max_length=20)),
                ('log_back', models.CharField(default='未签退', max_length=20)),
                ('isActive', models.CharField(default='正常', max_length=20)),
            ],
            options={
                'db_table': 'attendance_status',
                'verbose_name_plural': 'attendance_status',
            },
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_section', models.CharField(max_length=20)),
                ('Modify_previous_information', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=120)),
                ('user_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cwa.Attendance_status')),
            ],
            options={
                'db_table': 'extras',
                'verbose_name_plural': 'extras',
            },
        ),
    ]
