# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-27 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('receivers', models.CharField(max_length=200)),
                ('copy_to', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '邮件',
                'verbose_name_plural': '邮件',
                'db_table': 'email',
            },
        ),
    ]
