# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-27 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_name', models.CharField(max_length=30, unique=True)),
                ('em_age', models.IntegerField()),
                ('em_born', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254)),
                ('email_pword', models.CharField(max_length=30)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Users')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'employee',
            },
        ),
    ]
