# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-27 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meid', models.CharField(db_index=True, max_length=30)),
                ('mesytime', models.CharField(db_index=True, max_length=30)),
                ('date', models.CharField(db_index=True, max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('meplace', models.CharField(max_length=30)),
                ('metopic', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500, null=True)),
                ('statu', models.CharField(default='未开', max_length=50)),
                ('meinitiator', models.CharField(max_length=30)),
                ('merecorder', models.CharField(max_length=30)),
                ('meattendee', models.CharField(max_length=500)),
                ('mepresent', models.CharField(max_length=500, null=True)),
                ('menopresent', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': '会议',
                'verbose_name_plural': '会议',
                'db_table': 'meeting',
            },
        ),
    ]
